In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('deliveries.csv')

In [4]:
df

,match_no,date,stage,venue,batting_team,bowling_team,innings,over,striker,bowler,runs_of_bat,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder
0,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.1,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN
1,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.2,de Kock,Hazlewood,4,0,0,0,0,0,NaN,NaN,NaN
2,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.3,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN
3,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.4,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN
4,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.5,de Kock,Hazlewood,0,0,0,0,0,0,caught,de Kock,Jitesh Sharma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17178,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.2,Shashank Singh,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN
17179,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.3,Shashank Singh,Hazlewood,6,0,0,0,0,0,NaN,NaN,NaN
17180,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.4,Shashank Singh,Hazlewood,4,0,0,0,0,0,NaN,NaN,NaN
17181,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.5,Shashank Singh,Hazlewood,6,0,0,0,0,0,NaN,NaN,NaN
17182,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.6,Shashank Singh,Hazlewood,6,0,0,0,0,0,NaN,NaN,NaN

In [5]:
df['balls_delivered'] = (
    df['over'].astype(str).str.split('.').str[0].astype(int) * 6
    + df['over'].astype(str).str.split('.').str[1].astype(int)
)

In [6]:
df

,match_no,date,stage,venue,batting_team,bowling_team,innings,over,striker,bowler,runs_of_bat,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder,balls_delivered
0,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.1,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN,1
1,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.2,de Kock,Hazlewood,4,0,0,0,0,0,NaN,NaN,NaN,2
2,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.3,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN,3
3,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.4,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN,4
4,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.5,de Kock,Hazlewood,0,0,0,0,0,0,caught,de Kock,Jitesh Sharma,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17178,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.2,Shashank Singh,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN,116
17179,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.3,Shashank Singh,Hazlewood,6,0,0,0,0,0,NaN,NaN,NaN,117
17180,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.4,Shashank Singh,Hazlewood,4,0,0,0,0,0,NaN,NaN,NaN,118
17181,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.5,Shashank Singh,Hazlewood,6,0,0,0,0,0,NaN,NaN,NaN,119
17182,74,"Jun 03, 2025",Playoffs stage,"Narendra Modi Stadium, Ahmedabad",PBKS,RCB,2,19.6,Shashank Singh,Hazlewood,6,0,0,0,0,0,NaN,NaN,NaN,120

In [7]:
df.to_csv('deliveries.csv',index=False)